# .gitlab-ci.yml
image: crystallang/crystal:latest

variables:
  DOCS_PATH: docs-output

cache:
  paths:
    - lib/

before_script:
  - apt-get update -qq && apt-get install -y -qq libssl-dev git
  - shards install

stages:
  - test
  - build
  - docs
  - pages

test:
  stage: test
  script:
    - crystal spec
  artifacts:
    when: always
    paths:
      - spec/output/
    reports:
      junit: spec/output/junit.xml
  only:
    - tags
  except:
    - branches

build:
  stage: build
  script:
    - crystal build src/telecr.cr -o telecr
    - crystal build bin/telecr-ssl.cr -o telecr-ssl
  artifacts:
    paths:
      - telecr
      - telecr-ssl
    expire_in: 1 week
  only:
    - tags
    - manual

docs:
  stage: docs
  script:
    - crystal docs --output=$DOCS_PATH
  artifacts:
    paths:
      - $DOCS_PATH
    expire_in: 1 week
  only:
    - main

pages:
  stage: pages
  script:
    - mv $DOCS_PATH public
  artifacts:
    paths:
      - public
  only:
    - main
  dependencies:
    - docs